@IndieAPI.Api_HostAddress = http://localhost:5235

#if (EnableOpenAPI)
GET {{IndieAPI.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###
#endif

GET {{IndieAPI.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
