name: Test and Cover

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '11.0.x' ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore backend/

    - name: Build
      run: dotnet build --no-restore backend/

    - name: Test
      run: |
        dotnet test backend/IndieAPI.Tests/IndieAPI.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
    - name: Upload coverage report to Coveralls
      if: ${{ matrix.dotnet-version == '11.0.x' }}
      continue-on-error: true
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: ./backend/IndieAPI.Tests/coverage.info
